export enum Departamentos {
  ANTIONQUI = 'Antioquia',
  ATLANTIDO = 'Atlántico',
  BOGOTA = 'Bogotá',
  BOLIVAR = 'Bolívar',
  BOYACA = 'Boyacá',
  CALDAS = 'Caldas',
  CAQUETA = 'Caquetá',
  CASANARE = 'Casanare',
  CAUCA = 'Cauca',
  CESAR = 'Cesar',
  CORDOBA = 'Córdoba',
  CUNDINAMARCA = 'Cundinamarca',
  HUILA = 'Huila',
  GUAJIRA = 'La Guajira',
  MAGDALENA = 'Magdalena',
  META = 'Meta',
  NARIÑO = 'Nariño',
  NORTE_SANTANDER = 'Norte de Santander',
  QUINDIO = 'Quindío',
  RISARALDA = 'Risaralda',
  SANTANDER = 'Santander',
  SUCRE = 'Sucre',
  TOLIMA = 'Tolima',
  VALLE_DEL_CAUCA = 'Valle del Cauca',
  OTRO = 'Otro'
}
